### ISSUE TITLE
Delete the useless globalobjects and localobjects CR when loading data into vineyard cluster on kubernetes

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1150]
Describe your problem
---------------------

When using the vineyard cluster on kubernetes and loading data into vineyard, we find some extra CRs like `vineyard::ParallelStream` and `vineyard::StreamCollection` will be created and it will confuse users to find the real data.

Expected
---------

We want these useless CRs will not to be created.

**Comment by dashanji** [comment]
A possible way is to add some labels to these CRs while creating in the vineyard, and then the Controller needs to delete them for a while. However, using this method to delete CR will have a certain delay. The best way is not to generate corresponding CR in the vineyardd.

**Comment by sighingnow** [comment]
Fixed in the io adaptor itself.

**Comment by dashanji** [comment]
The `vineyard::ParallelStream` globalobjects still exist but the metadata is missed. It looks like we need to add some judgements before vineyardd creates CR.
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/71587243/216227701-15e36568-28fe-4f29-9ba5-22d63f742f88.png">

**Comment by sighingnow** [comment]
I would take a look. But I think it might be a seperate issue.

**Comment by dashanji** [comment]
Thanks, I opened another issue https://github.com/v6d-io/v6d/issues/1174. 

Closed here.
