### ISSUE TITLE
Json parse error with multiple remote blob writes

### ISSUE THREAD

**Issue by watch24hrs-iiitd** [v6d-io/v6d#1430]
Describe your problem
---------------------

When doing multiple remote blob writes, I run into a 
```
vineyard._C.InvalidException: Invalid: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```

----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version (`uname -a`): 
```
Linux 5.19.0-45-generic
```
2. The version of vineyard you use (`vineyard.__version__`): `0.15.0`
3. Versions of crucial packages, such as gcc, numpy, pandas, etc.: `11.3.0`
4. Full stack of the error (if there are a crash):
```
remote_blob_id = client.create_remote_blob(blob_builder)
vineyard._C.InvalidException: Invalid: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```
5. Minimized code to reproduce the error:
```python
"""
Vineyard launched using: python3 -m vineyard --size 5G --socket=/tmp/vineyard.sock 
"""
import vineyard
import os


client = vineyard.connect("localhost", 9600)


for i in range(100):
    print(f"Writing {i} blob")
    payload = os.urandom(1024 * 1024 * 100)
    blob_builder = vineyard.RemoteBlobBuilder(len(payload))
    blob_builder.copy(0, payload)

    have_written = False
    while not have_written:
        try:
            remote_blob_id = client.create_remote_blob(blob_builder)
            have_written = True
            print(f"Successfully written {i} blob")
        except vineyard.NotEnoughMemoryException:
            print(f"Not enough memory, retrying {i} blob")
            continue
```

----------------------------------------------------------------------

**Comment by sighingnow** [comment]
Thanks for reporting. I will take a try to reproduce.

**Comment by sighingnow** [comment]
Fixed in the latest bugfix release, try `pip3 install vineyard==0.15.1`.

**Comment by watch24hrs-iiitd** [comment]
Hi, this issue still prevails, as in the above code snippet, when Vineyard is out of memory, I should keep retrying, although I get a 
```
vineyard._C.IOErrorException: IOError: Send message failed: Connection reset by peer
```
on the client, and my vineyard server crashes with 
```
E20230626 18:17:15.140587 15969 socket_server.cc:203] json: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '('
E20230626 18:17:15.141117 15974 socket_server.cc:203] json: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '�'

Unhandled exception:
  std::exception:what(): [json.exception.type_error.316] invalid UTF-8 byte at index 130: 0xF7
  ```

**Comment by sighingnow** [comment]
Looks strange. Let me take a try about OOM.

**Comment by sighingnow** [comment]
> Looks strange. Let me take a try about OOM.

Hi @watch24hrs-iiitd,

The bug during OOM has been fixed in the latest release v0.15.2.
